### ISSUE TITLE
Change floating button action - replace Add New Feed (+) with Mark As Read (✓)

### ISSUE THREAD

**Issue by gskoljarev** [readrops/Readrops#133]
- replace float button action as in title
- move "Add Feed" to the sidebar, above "Articles"

Great little app, devs!

**Comment by GLLM** [comment]
I would add that this "mark as read" Burton would be immensely more usefull if it could act like a toggle (i.e mark as read or unread) rather than simply marking unread articles as read ...
The icon should adapt to the currently article read-ness status

As a matter of fact, i spend a lot of times unhiding read articles (as i only show unread ones) to set as unread articles i want to re-read later.
Such Burton would be fantastic.

**Comment by Shinokuni** [comment]
Mark all articles as read FAB added in 2.0. The first beta is [available](https://github.com/readrops/Readrops/releases/tag/v2.0-beta01) to test if you would like so.
