### ISSUE TITLE
[Feature]: http://127.0.0.1:8080 results in HTTP 503

### ISSUE THREAD

**Issue by Emporea** [readrops/Readrops#219]
**Is your feature request related to a problem? Please describe.**
Lets say you have freshrss locally or tunneld via ssh available on port 8080 and you want to connect via readdrops, its not possible. Using the same url via a browser works flawlessly.

Why is that the case? Is it because of http being unsupported or some other reason?

I would appreciate to be able to use readdrops for a freshrss installation available via http and a localhost port.

**Comment by talkingseedling** [comment]
Is FreshRSS installed on a computer, accessible via 127.0.0.1 on that same computer, and then you're trying to access it from a different device, your phone with readrops, via 127.0.0.1? If so 127.0.0.1 is reflective and points to the device itself, so unless you have freshrss installed on your phone, you'll need to use the IP address of the computer freshrss is installed on.

**Comment by Roan-V** [comment]
I'm running into (what I assume) is the same issue.
Just installed Readrops from F-Droid (2.0.1), trying to configure FreshRSS

FreshRSS is running locally on my NAS, with IP 10.1.1.6 on port 81
Going to that address and logging in on a webbrowser works just fine
Doing the same on Readrops gets me the same 503 error as above

Spitballing here, because adb logcat wasn't much help, can Reardrops handle IP:port "url's"?
Does it expect the default port or an actual url maybe?

**Comment by Roan-V** [comment]
I have trying to set up split DNS somewhere on my ToDo list :P
Setting up HTTPS certs (without manually handing them out) but keeping the services only accessible when local (or VPN'd in) is all a bit janky sadly.

**Comment by Shinokuni** [comment]
Okay so to answer some questions here, Readrops network security config currently allows all kind of clear text traffic. So local URLs should work out of the box. It is possible that some of them need to be set explicitly otherwise could be blocked by the system, but all of that is unclear right now.

I will check this out.
