### ISSUE TITLE
Sync with NC

### ISSUE THREAD

**Issue by hovancik** [readrops/Readrops#49]
Hi, 

was testing the integration with Nextcloud and would be awesome if I could sync read items. 

I've marked stuff read on NC but it's not marked read in Readrops after refresh.

**Comment by Shinokuni** [comment]
Hello,

Items read state sync should be working with Nextcloud News. I know I have recently fixed something related to this, but I am not sure if it has been released. I will check.

**Comment by hovancik** [comment]
Ok, I tried F-Droid version

**Comment by deadwax** [comment]
Perhaps related: I can't see items marked as read in NC. If I log into the NC web interface and mark them as unread they then show up in readrops.  Reading them in readrops then marks them as read, but only those read items show up when "show read items" is ticked, not those read outside readrops.

**Comment by Shinokuni** [comment]
So @hovancik I did fix items read state sync but only in develop. It is fixed in dfaec3bdb13c09b10661c986d4ae4cbf274d5080. I will make a new release soon.

@deadwax I think it is indeed related. Currently, you get only the first item read outside Readrops when syncing, others are ignored. But items read in Readrops will show up as read in News.
