### ISSUE TITLE
A variety of different errors

### ISSUE THREAD

**Issue by dngray** [readrops/Readrops#70]
Hi,

When importing my RSS feeds I noticed a variety of different errors. They all seem to work in [Newsboat](https://newsboat.org). (This is under a local account).

Maybe you could take a look?

| Feed                                                                                                  | Error                                                                                        |
|-------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------|
| [andrew pillar (RSS)](https://andrewpillar.com/rss.xml)                                               | Failure when parsing feed                                                                    |
| [andrew pillar (Atom)](https://andrewpillar.com/atom.xml)                                             | Works                                                                                        |
| [Cory Doctorow's craphound.com](https://craphound.com/feed)                                           | Failure when parsing feed                                                                    |
| [Ctrl blog](https://feed.ctrl.blog/latest.atom)                                                       | Failure when parsing feed                                                                    |
| [DUALUSE](https://dualuse.io/index.xml)                                                               | Failure when parsing feed                                                                    |
| [Deeplinks](https://www.eff.org/rss/updates.xml)                                                      | Failure when parsing feed                                                                    |
| [Fastmail blog](https://fastmail.blog/rss/)                                                           | Failure when parsing feed                                                                    |
| [Full Disclosure](https://seclists.org/rss/fulldisclosure.rss)                                        | Failure when parsing feed                                                                    |
| [Latacora](https://latacora.micro.blog/feed.xml)                                                      | Failure when parsing feed                                                                    |
| [Mailfence Blog](https://blog.mailfence.com/feed)                                                     | Failure when parsing feed                                                                    |
| [Signal Blog](https://signal.org/blog/rss.xml)                                                        | Failure when parsing feed                                                                    |
| [Stephen Mann](http://stephenmann.io/index.xml)                                                       | Failure when parsing feed                                                                    |
| [TED Talks Daily (SD video)](https://www.ted.com/feeds/talks.rss)                                     | Failure when parsing feed                                                                    |
| [Tencent Security Xuanwu Lab](https://xlab.tencent.com/en/feed/)                                      | Failure when parsing feed                                                                    |
| [VICE US - undefined US](https://www.vice.com/en_us/rss/section/tech)                                 | Failure when parsing feed                                                                    |
| [xda-developers](https://www.xda-developers.com/feed/)                                                | Failure when parsing feed                                                                    |
| [news.ycombinator.com](https://news.ycombinator.com/rss)                                              | Failure when parsing feed                                                                    |
|                                                                                                       |                                                                                              |
| [Bryan Braun - Designer/Developer](https://feeds.feedburner.com/bryanbraun)                           | Network failure when accessing feed                                                          |
| [Dan Luu](https://danluu.com/atom.xml)                                                                | Network failure when accessing feed                                                          |
| [Google Online Security Blog](https://security.googleblog.com/feeds/posts/default)                    | Network failure when accessing feed                                                          |
| [IEEE Spectrum Recent Content full text](https://spectrum.ieee.org/rss/fulltext)                      | Network failure when accessing feed                                                          |
| [Linux Kernel Newbies](https://kernelnewbies.org/RecentChanges?action=rss_rc&amp;unique=1)            | Network failure when accessing feed                                                          |
| [WeeChat news](https://weechat.org/feeds/news)                                                        | Network failure when accessing feed                                                          |
| [Wired: Feed: All Latest](https://www.wired.com/feed/security/rss)                                    | Network failure when accessing feed                                                          |
| [dkg's blog](https://dkg.fifthhorseman.net/blog/feeds/all.atom.xml)                                   | Network failure when accessing feed                                                          |
|                                                                                                       |                                                                                              |
| [AnandTech](https://www.anandtech.com/rss)                                                            | Validates but seems to be empty                                                              |
| [Dark Reading:](https://www.darkreading.com/rss_simple.asp)                                           | Validates but seems to be empty                                                              |
| [Debian News](https://www.debian.org/News/news.rdf)                                                   | Validates but seems to be empty                                                              |
| [Debian Security](https://www.debian.org/security/dsa)                                                | Validates but seems to be empty                                                              |
| [Discover Dev](https://www.discoverdev.io/rss.xml)                                                    | Validates but seems to be empty                                                              |
| [Disroot Blog](https://disroot.org/en/blog.rss)                                                       | Validates but seems to be empty                                                              |
| [HashiCorp Blog](https://www.hashicorp.com/blog/feed.xml)                                             | Validates but seems to be empty                                                              |
| [Image Sensors World](https://image-sensors-world.blogspot.com/feeds/posts/default)                   | Validates but seems to be empty                                                              |
| [Neopythonic](https://neopythonic.blogspot.com/feeds/posts/default)                                   | Validates but seems to be empty                                                              |
| [O'Reilly Radar](https://www.oreilly.com/radar/feed/index.xml)                                        | Validates but seems to be empty                                                              |
| [Project Zero](https://googleprojectzero.blogspot.com/feeds/posts/default)                            | Validates but seems to be empty                                                              |
| [Techdirt.](https://feeds.feedburner.com/techdirt/feed)                                               | Validates but seems to be empty                                                              |
| [Threat Research](https://www.fireeye.com/blog/threat-research/_jcr_content.feed)                     | Validates but seems to be empty                                                              |
| [meli MUA](https://meli.delivery/rss.xml)                                                             | Validates but seems to be empty                                                              |
|                                                                                                       |                                                                                              |
| [LWN.net](https://lwn.net/headlines/newrss)                                                           | `Attempt to invoke virtual method 'int java.lang.String.length() on a null object reference` |
| [Slashdot](http://rss.slashdot.org/Slashdot/slashdotMain)                                             | `Attempt to invoke virtual method 'int java.lang.String.length() on a null object reference` |
| [has_many :codes](https://vitobotta.com/feed)                                                         | `Attempt to invoke virtual method 'int java.lang.String.length() on a null object reference` |
| [Level1Techs (Youtube)](https://www.youtube.com/feeds/videos.xml?channel_id=UC4w1YQAJMWOz4qtxinq55LQ) | `Attempt to invoke virtual method 'int java.lang.String.length() on a null object reference` |
|                                                                                                       |                                                                                              |
| [Posteo.de - Aktuelles](https://posteo.de/en/blog/feed?format=atom)                                   | `length=194902; index=-1`                                                                    |

**Comment by Shinokuni** [comment]
Wow, thanks for the list. I will definitely check them all.

**Comment by dngray** [comment]
> Wow, thanks for the list. I will definitely check them all.

No problem I figured it would be helpful. Main reason I switched to readrops is it seems to be the only RSS client in f-droid that supports grouped folders.

Curious question about that, is it legal to have groups within groups? According to the newsboat docs it seems possible: [3.3.2. Other readers (via OPML)](https://newsboat.org/releases/2.19/docs/newsboat.html#_other_readers_via_opml).

**Comment by Shinokuni** [comment]
Hello,

So I've tested all your feeds. You can take a look below.


Feed | Error | Status
-- | -- | --
andrew pillar (RSS) | Failure when parsing feed |  Works
andrew pillar (Atom) | Works | /
Cory Doctorow's craphound.com | Failure when parsing feed | Works
Ctrl blog | Failure when parsing feed | Works
DUALUSE | Failure when parsing feed | Works
Deeplinks | Failure when parsing feed | Works (but creator tag support lost)
Fastmail blog | Failure when parsing feed | Works
Full Disclosure | Failure when parsing feed | Works
Latacora | Failure when parsing feed | Has empty titles
Mailfence Blog | Failure when parsing feed | Works
Signal Blog | Failure when parsing feed | Works
Stephen Mann | Failure when parsing feed | Expired certificate
TED Talks Daily (SD video) | Failure when parsing feed | Works
Tencent Security Xuanwu Lab | Failure when parsing feed | 404 not found
VICE US - undefined US | Failure when parsing feed | Works
xda-developers | Failure when parsing feed | Works
news.ycombinator.com | Failure when parsing feed | Works
Bryan Braun - Designer/Developer | Network failure when accessing feed | Now works
Dan Luu | Network failure when accessing feed | No more network failure but has a wrong rss url
Google Online Security Blog | Network failure when accessing feed | Works
IEEE Spectrum Recent Content full text | Network failure when accessing feed | Works
Linux Kernel Newbies | Network failure when accessing feed | No more network failure, but RSS 1.0 is not supported
WeeChat news | Network failure when accessing feed | Works
Wired: Feed: All Latest | Network failure when accessing feed | Works
dkg's blog | Network failure when accessing feed | Works
AnandTech | Validates but seems to be empty | Works
Dark Reading: | Validates but seems to be empty | Works
Debian News | Validates but seems to be empty | RSS 1.0 not supported
Debian Security | Validates but seems to be empty | RSS 1.0 not supported
Discover Dev | Validates but seems to be empty | Works
Disroot Blog | Validates but seems to be empty | Weird redirection to https://disroot.org/en/blog
HashiCorp Blog | Validates but seems to be empty | Works
Image Sensors World | Validates but seems to be empty | Works
Neopythonic | Validates but seems to be empty | Works
O'Reilly Radar | Validates but seems to be empty | atom link is https://www.oreilly.com/radar/feed/ which returns 403
Project Zero | Validates but seems to be empty | Works
Techdirt. | Validates but seems to be empty | Works
Threat Research | Validates but seems to be empty | Works
meli MUA | Validates but seems to be empty | Works
LWN.net | Attempt to invoke virtual method 'int java.lang.String.length() on a null object reference | RSS 1.0 is not supported
Slashdot | Attempt to invoke virtual method 'int java.lang.String.length() on a null object reference | RSS 1.0 is not supported
has_many :codes | Attempt to invoke virtual method 'int java.lang.String.length() on a null object reference | Works
Level1Techs (Youtube) | Attempt to invoke virtual method 'int java.lang.String.length() on a null object reference | Works
Posteo.de - Aktuelles | length=194902; index=-1 | Works

Thanks to that, I was able to fix those errors:
- absence of guid tag (optional tag but Readrops relied ont it for every feed item)
- favicon fetch bug fixed for #71
- unsupported multiple creator tags
- unsupported multiple image tags in RSS channel
- enclosure tag required attributes
- unsupported date formats
- ATOM format detection bug

I wasn't able to fix them all because of various issues. The main one is that Readrops doesn't support RSS 1.0. Some feeds have their embedded RSS url unreachable (wrong url, 404, 403, etc). There could be a fix for this case but I'm unsure about what to do here.

I wonder if I shouldn't replace SimpleXML which is the XML framework Readrops currently uses as it is unreliable for this kind of use case and as I'm really fed up of fixing things because of it.
